#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, r11f_g11f_b10f) uniform readonly image2D inputImage;
layout (binding = 1) uniform writeonly image2D outputImage;

vec4 ConvertColor(in vec4 inputColor) 
{
	vec3 irgb = vec3(1.0f) - inputColor.rgb;
	return vec4(irgb, inputColor.a);
}

void main()
{
	// 入力イメージのカラーを取得する
	vec4 inputColor = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.xy));

	// 入力カラーを加工
	vec4 result = ConvertColor(inputColor);

	// 加工したカラーを出力
	imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), result);
}